# Data sources


## Sources

**Correlates of War**

We got our main war data from The Correlates of War (COW) Project by David Singer and Mel Small. Singer and Small have utilized a classification of wars that is based upon the status of territorial entities, in particular focusing on those that are classified as members of the inter-state system (referred to as “states”). 

Inter-state wars were those that were conducted between or among members of the interstate system. For example, World War I and World War II would be considered inter-state wars. 


Intra-state wars are wars that predominantly take place within the recognized territory of a state. Intra-state wars have been subdivided into three general types, based upon the status of the combatants: civil wars involve the government of the state against a non-state entity; regional internal wars(war type 6)  involve the government of a regional subunit against a non-state entity; and intercommunal wars(war type 7) involve combat between/among two or more non-state entities within the state. Civil wars have then been subdivided further into two types; those for control of the central government(war type 4), and those involving disputes over local issues(war type 5). The U.S. civil war will be considered civil wars for central control(war type 4). 


Non-state wars include those wars conducted by non-system member actors that take place beyond the confines of one state. Non -state wars have been subdivided into two types: wars between or among non-state entities that take place in non-state territory (war type 8, of which there are sixty-one) and wars between non-state armed groups that take place across state borders (war type 9, of which they have identified one), are included in the Non-State War dataset. All 62 non-state wars took place in the 1500s. 

Extra-state wars take place between a state(s) and a nonstate entity outside the borders of the state and were subdivide into two types: colonial (war type 2) and imperial(war type 3). A colonial extra-state war tends to occur when a colony rebels and tries to become
independent. In addition, the colonial people may resort to war to seek relief on a policy question, rather than seeking independence. In imperial wars, the system member fights an adversary that is, “an independent political entity that did not qualify for system membership because of serious limitations on its independence, a population insufficiency, or a failure of other states to recognize it as a legitimate member.”  In practice, most of the imperial wars in this dataset involved a state’s attempt to colonize a previously independent geographic area, though extra-state wars can also be fought against non-territorially based
entities.

Here is a summary of typology of wars defined by Singer and Small:

1. Inter-state wars (war type 1)

2. Extra-state wars
      + Colonial-conflict with colony (war type 2)
      + Imperial-state vs nonstate (war type 3)
      
3. Intra-state wars
      + Civil Wars
          * For central control (war type 4)
          * Over local issues (war type 5)
      + Regional internal (war type 6)
      + Intercommunal (war type 7)
      
4. Non-state wars
      + In nonstate territory (war type 8)
      + Across state borders (war type 9)

Link: https://correlatesofwar.org/



**Maddison Project Database 2018**

Maddison Project Database provided us with historic population and real GDP per capita data. 
The Maddison Project Database provides information on comparative economic growth and income levels over the very long run.

Link: https://www.rug.nl/ggdc/historicaldevelopment/maddison/releases/maddison-project-database-2018

**Our World in Data**

Our World in Data is a collaborative effort between the University of Oxford, who are the scientific editors of the website content; and the non-profit organization Global Change Data Lab, which publishes and maintains the website and the data tools. This is as part of the Oxford Martin Program on Global Development.

Primary School Enrollment dataset contains data regarding the primary school enrolment of various countries. The variables included in the dataset are CountryName, CountryCode, year and percentage enrolment in primary schools of the country.

Military Expenditure dataset contains data regarding military expenditure (as a share of GDP) of various countries over different years. The variables included in the dataset are CountryName, CountryCode, year and military expenditure as a share of GDP over the years.

Human Development Index dataset contains data regarding the Human Development Index of various countries over different years. The variables included in the dataset are CountryName, CountryCode, year and HDI value.


## Format 

All data we found for this project came in `csv` format.

## Variables

**Correlates of War**


Variables         | Description
----------------- | ------------------------------------------------------------------------------------------------
WarNum            | the number assigned to the war
WarName           | the name given to the war
WarType           | 1 = Inter-state war; 2 = Colonial War; 3 = Imperial War; 4 = Civil war for central control; 5 = Civil war over local issues; 6 = Regional internal; 7 = Intercommunal; 8 = wars between or among non-state entities that take place in non-state territory； 9 = wars between NSAs that take place across state borders
Ccode             | the System Membership number (or Country Code) for the state participant
Ccode1            | the System Membership number (or Country Code) for the participant on Side A of the war; -8 = Not Applicable (the participant is not a state) or there is no additional state on Side A
CcodeA            | the Country Code or System Membership number for the participant on Side A of the war; -8 = Not Applicable (the participant is not a state)
State Name        | the name of the System Member
StartMonth1       | the month in which sustained combat began: -9 = month unknown
StartDay1         | the day on which sustained combat began: -9 = day unknown
StartYear1        | the year in which sustained combat began: -9 = year is unknown
EndMonth1         | the month in which sustained combat ended: -7 = war ongoing as if 12/31/2007, -9 = month unknown
EndDay1           | the day on which sustained combat ended: -7 = war ongoing as if 12/31/2007, -9 = day unknown
EndYear1          | the year in which sustained combat ended: -7 = war ongoing as if 12/31/2007, -9 = year unknown
StartMonth2       | after a break in the fighting, the month in which sustained combat resumes: -9 = month unknown, -8 = not applicable
StartDay2         | after a break in the fighting, the day on which sustained combat resumes: -9 = month unknown, -8 = not applicable
StartYear2        | after a break in the fighting, the year in which sustained combat resumes: -9 = year unknown, -8 = not applicable
EndMonth2         | after fighting resumes, the month in which sustained combat ended, or the month of the last major engagement after which fatalities declined below the war fatality threshold: -7 = war ongoing as if 12/31/2007, -9 = month unknown, -8 = not applicable
EndDay2           | after fighting resumes, the day on which sustained combat ended, or the day after the last major engagement after which fatalities declined below the war fatality threshold: -7 = war ongoing as if 12/31/2007, -9 = day unknown, -8 = not applicable
EndYear2          | after fighting resumes, the year in which sustained combat ended, or the year of the last major engagement after which fatalities declined below the war fatality threshold: -7 = war ongoing as if 12/31/2007, -9 = year unknown, -8 = not applicable
TransFrom         | the WarNum of a preceding war that was transformed into this inter-state war: -8 = Not applicable
Interven          | was there an additional state that intervened in the war? 0 = no, 1 = yes
WhereFought       | Region(s) where combat involving the state occurred.
Initiator         | whether the state initiated the war(some datasets encoded this variable differently) 1 = Yes 2 = No
TransTo           | the WarNum of the war that this war transformed into, -8 = Not applicable
Outcome           | 1 = Winner; 2 = Loser; 3 = Compromise/Tied; 4 = The war was transformed into another type of war; 5 = The war is ongoing as of 12/31/2007; 6 = Stalemate; 7 = Conflict continues at below war level; 8 = changed sides
SideADeaths       | the battle-related combatant fatalities suffered by the Side A participant: - 8 = not applicable, -9= data unknown
SideBDeaths       | the battle-related combatant fatalities suffered by the Side B participant: -8 = not applicable, -9= data unknown
TotalCombatDeaths | the combination of Side A Deaths and Side B. Deaths. If the specific fatalities of the Sides are unknown, a total combatant fatality figure may be provided, -9 = data unknown
BatDeaths         | the battle-related combatant fatalities suffered by the state: -9 = data unknown
NonState Deaths   | the battle-related combatant fatalities suffered by the nonstate participant: -8 = not applicable, -9= data unknown
Version           | Version of the data = 4.0 



**Maddison Project Database 2018**

Variables      | Description
-------------- | --------------------------
countrycode    | 3-letter ISO country code
country        | Country name
year           | Year
cgdppc         | Real GDP per capita in 2011US dollars, multiple benchmarks 
rgdpnapc       | Real GDP per capita in 2011US dollars, 2011 benchmark 
pop            | Population, mid-year (thousands)
i_cig          | observation is extrapolated (0), benchmark (1), or interpolated (2)
i_bm           | For benchmark observations: 1: ICP PPP estimates, 2: Historical income benchmarks, 3: Real wages and urbanization, 4: Multiple of subsistence, 5: Braithwaite (1968) PPPs


## Additonal Information

For inter-state war dataset, most wars have multiple rows of observations, where the number of rows is the number of participants of that war. For instance, the Franco-Spanish War is between Spain and France and there is one row of observation for each participating country. 

For intra-state war dataset and extra-state war dataset, most wars also have multiple rows of observations, where the number of rows is the maximum number of participants on either side of that war. For instance, Ottoman Empire is on side A of the Greek Independence War and side B consists of Greeks, United Kingdom, France and Russia. Therefore, the number of rows got is 4 for Greek Independence War. We also note that in the case that one side has fewer participants than the other, the participants will not be repeated but will be coded as -8(not applicable). For the same example as above, side A only has Ottoman Empire and Ottoman Empire is in one row while the other three rows on the same war has -8 for side A, instead of repeating Ottoman Empire. 

For non-state war dataset, each war only has one row of observation. 


## Issues with Datasets

**Correlates of War**

There is no war data after 2010 so the war dataset is not exactly up to date. There is only one observation for type 9 war data which is the non-state wars between non-state armed groups that take place across state borders. Furthermore, the battle death data is only an estimate: they utilized a 3:1 ratio of wounded to killed in order to calculate the number of battle-related deaths when only casualty estimates are available. However, the dataset is quite extensive with data dating back to the 16th century and other sources also only provide estimated values for death. This dataset still provides us with plenty insights on the relative magnitude of the costs of war participation.

**Maddison Project Database 2018**

While this dataset seems to be the most extensive as it comes to historic data on real GDP per capita and population, some of the data are extrapolated.  

**Primary School Enrolment, Military Expenditure as a share of GDP, Human Development Index**

All of them don't have data regarding all countries involved in World War 1 (or 2). We chose those countries that were a part of WW1 or WW2 (but all were not present). Another issue was that even if countries were available, data concerning them for all years were not available. We could only analyze those that matched the timeline of WW1 and WW2. 
