# Data transformation

In this chapter, we discussed the process of getting the data into a form in which we could work with it in R.


## COW Data

The 4 data sets we downloaded as csv files from COW website are pretty clean with each variable defined clearly. Generally, for each question we are interested in exploring, we selected the related variables only and transformed them into the format for plots, by dplyr package functions such as mutate(), select(), filter(), group_by(), summarise() and tidyr package functions like gather() and spread(). For example, to answer what types of wars happened most frequently, for each data set, we first added one column for its general war type, and then selected `WarNum`, `WarName`, and `WarType`, and finally combined 4 data frames by row. Specially, we changed the `WarType` as a factor  to war type plus brief description. For another instance, to answer which states suffered from most losses of human beings in battles, we picked state name and number of battle death for each data set, and changed the data type of number of battle deaths into uniform numeric data type without comma. Then we replaced negative number of battle deaths with `NA`. Then the cleaned data is ready for row binding and the last step includes grouping by state and counting the sum of deaths for each state. Other data transformation processes are similar except for selection of different set of columns.

In order to answer some other questions incorporating both states and wars, for example, what states had most which type of wars, we performed more steps before combining by rows. It should be noticed that data sets of non-state wars, intra-state wars, and extra-state wars has each war as one row, which means there would be at least two states or sides for each row. Thus, in the three data sets, war name and war code are unique. On the other hand, in the inter-state data set, the **combination** of war name (war code) and state name is unique, which means one wars may range across multiple rows with each row recording information of one state involved in that war. It is the major different between these two kinds of data sets and we transformed data sets of intra-state, extra-state, and non-state wars into the format of data for inter-state wars. In other words, after the transformation, when all wars appear in one dataset, the pair of (WarName, StateName) is unique. The transformation algorithm is described below:

**Intra-state**: 
if a war appears with two sides, then:  
  * if CcodeA is valid, add new row (WarNum, WarName, WarType, StateName=sideA, ccode=CcodeA, BatDeath = SideADeaths) to data frame sideA;
  * if CcodeB is valid, add new row (WarNum, WarName, WarType, StateName=sideB, ccode=CcodeB, BatDeath = SideBDeaths) to data frame sideB;
  * row-bind sideA and sideB to form intra-state data frame with 6 variables WarNum, WarName, WarType, StateName, ccode, BatDeath.

**Inter-state**: 
if ccode is valid, then
  * add new row (WarNum, WarName, Type, StateName, ccode, BatDeath) to data frame inter-state with 6 variables WarNum, WarName, WarType, StateName, ccode, BatDeath.
  
**Extra-state**:
there are no wars with both SideA and SideB existing, which means each row represents a war with one side record and then:
  * we can then safely add BatDeath and NonStateDeaths as total BatDeath
  * if ccode1 is valid, add new row (WarNum, WarName, WarType, StateName=SideA,ccode=ccode1, BatDeath) to data frame sideA;
  * if ccode2 is valid, add new row (WarNum, WarName, WarType, StateName=SideB,ccode=ccode2, BatDeath) to data frame sideb;
  * row-bind sideA and sideB to form extra-state data frame with 6 variables WarNum, WarName, WarType, StateName, ccode, BatDeath.

**Non-state**: these wars are not about countries or states, and thus we did not take them into consideration in this particular case.  

Note that valid here means the ccode is not negative based on the codebook of COW and it exists in another data set provided by COW of a list of state and correspondong codes. Furthermore, all numbers of deaths were cleaned to become numbers.

## choropleth maps

When plotting choropleth maps, we found there are some states or countries that currently do not exist and consequently do not appear in R's world map data set, such as USSR. To deal with this issue, we recoded all countries that were in USSR during World War II as USSR and added those countries that still exist now into world data again. As a result, the world data set now should contain the geology data of all countries we have. 


## External Data


