# Conclusion

Discuss limitations and future directions, lessons learned.

Here are our most surprising findings:

- France initiated the most inter-state wars (8 wars), while U.S., Russia and Japan initiated the second most inter-state wars (7 wars).

- France, Romania, Bulgaria and Italy changed sides once during WW1.

- From the interactive parallel coordinate plot, we observed that while states that were not initiators of the wars tend to have lower battle deaths, USSR in WW2 did not follow that trend: even though it wasn't an initiator, it had the highest battle deaths in all countries. 

- Population for Japan increased steadily even during the two world wars and remained increasing even after those wars. 

- During WW1, primary school enrollment in Germany was unaffected and had been increasing steadily.

- There was no apparent effect of the world wars on overall Human Development indices.

As was discussed in the data section, there were some limitations in our datasets.

*Future Scope*:

- More work can be done trying to find out why certain countries who lost and initiated wars. More supplementary datasets such as technological development, higher education status, study on political climate of countries, etc can be used.

- Our current study focuses on comparison of effect of different wars on countries. In future, to shine some light on the negative and avoidable impacts of wars, a comparative study between two countries- one of them involved in wars and other not, can be done to draw conclusions as to the state of development of these countries given their involvement in wars.

- Our datasets also contained information about the location of wars. A study on the geographical location of war sites and its affect on neighboring geographical areas and population can be done.
