<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Missing values | Wars in History, 1816-2007</title>
  <meta name="description" content="Chapter 4 Missing values | Wars in History, 1816-2007" />
  <meta name="generator" content="bookdown 0.16 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Missing values | Wars in History, 1816-2007" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Missing values | Wars in History, 1816-2007" />
  
  
  

<meta name="author" content="Priyanka Lahoti, Hima Bindu Bhardwaj, Jasmine Bao, Yingnan Wu" />


<meta name="date" content="2019-12-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-transformation.html"/>
<link rel="next" href="results.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.49.4/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.49.4/plotly-latest.min.js"></script>
<link href="libs/parallel-coordinates-2.1.8/parcoords.css" rel="stylesheet" />
<script src="libs/parcoords-binding-1.0.0/parcoords.js"></script>
<script src="libs/d3-5.10.0/d3.min.js"></script>



<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Wars in History</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="data-sources.html"><a href="data-sources.html"><i class="fa fa-check"></i><b>2</b> Data sources</a><ul>
<li class="chapter" data-level="2.1" data-path="data-sources.html"><a href="data-sources.html#sources"><i class="fa fa-check"></i><b>2.1</b> Sources</a></li>
<li class="chapter" data-level="2.2" data-path="data-sources.html"><a href="data-sources.html#format"><i class="fa fa-check"></i><b>2.2</b> Format</a></li>
<li class="chapter" data-level="2.3" data-path="data-sources.html"><a href="data-sources.html#variables"><i class="fa fa-check"></i><b>2.3</b> Variables</a></li>
<li class="chapter" data-level="2.4" data-path="data-sources.html"><a href="data-sources.html#additonal-information"><i class="fa fa-check"></i><b>2.4</b> Additonal Information</a></li>
<li class="chapter" data-level="2.5" data-path="data-sources.html"><a href="data-sources.html#issues-with-datasets"><i class="fa fa-check"></i><b>2.5</b> Issues with Datasets</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>3</b> Data transformation</a><ul>
<li class="chapter" data-level="3.1" data-path="data-transformation.html"><a href="data-transformation.html#cow-data"><i class="fa fa-check"></i><b>3.1</b> COW data</a></li>
<li class="chapter" data-level="3.2" data-path="data-transformation.html"><a href="data-transformation.html#choropleth-maps"><i class="fa fa-check"></i><b>3.2</b> Choropleth maps</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="missing-values.html"><a href="missing-values.html"><i class="fa fa-check"></i><b>4</b> Missing values</a></li>
<li class="chapter" data-level="5" data-path="results.html"><a href="results.html"><i class="fa fa-check"></i><b>5</b> Results</a><ul>
<li class="chapter" data-level="5.1" data-path="results.html"><a href="results.html#general-edav"><i class="fa fa-check"></i><b>5.1</b> General EDAV</a><ul>
<li class="chapter" data-level="5.1.1" data-path="results.html"><a href="results.html#number-of-wars-by-type"><i class="fa fa-check"></i><b>5.1.1</b> Number of wars by type</a></li>
<li class="chapter" data-level="5.1.2" data-path="results.html"><a href="results.html#number-of-wars-by-state"><i class="fa fa-check"></i><b>5.1.2</b> Number of wars by state</a></li>
<li class="chapter" data-level="5.1.3" data-path="results.html"><a href="results.html#number-of-war-deaths"><i class="fa fa-check"></i><b>5.1.3</b> Number of war deaths</a></li>
<li class="chapter" data-level="5.1.4" data-path="results.html"><a href="results.html#correlation-between-wars-and-death-counts"><i class="fa fa-check"></i><b>5.1.4</b> Correlation between wars and death counts</a></li>
<li class="chapter" data-level="5.1.5" data-path="results.html"><a href="results.html#inter-state-wars-correlation-between-initiators-and-winners"><i class="fa fa-check"></i><b>5.1.5</b> Inter-state wars: Correlation between initiators and winners</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="results.html"><a href="results.html#world-war-i-and-world-war-ii"><i class="fa fa-check"></i><b>5.2</b> World War I and World War II</a></li>
<li class="chapter" data-level="5.3" data-path="results.html"><a href="results.html#external-statistics"><i class="fa fa-check"></i><b>5.3</b> External statistics</a><ul>
<li class="chapter" data-level="5.3.1" data-path="results.html"><a href="results.html#world-war-i"><i class="fa fa-check"></i><b>5.3.1</b> World War I</a></li>
<li class="chapter" data-level="5.3.2" data-path="results.html"><a href="results.html#world-war-ii"><i class="fa fa-check"></i><b>5.3.2</b> World War II</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="interactive-component.html"><a href="interactive-component.html"><i class="fa fa-check"></i><b>6</b> Interactive component</a></li>
<li class="chapter" data-level="7" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>7</b> Conclusion</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Wars in History, 1816-2007</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="missing-values" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Missing values</h1>
<p>From the codebook, we know that -9 is used to encode variable with unknown values. Therefore, we need to encode all variables with value -9 as NA. Note that the value -8 encodes “not applicable” which is different from missing.</p>
<p>Inter-state Wars Dataset</p>
<pre><code>##    BatDeath      WarNum     WarName     WarType       ccode   StateName 
##           1           0           0           0           0           0 
##        Side StartMonth1   StartDay1  StartYear1   EndMonth1     EndDay1 
##           0           0           0           0           0           0 
##    EndYear1 StartMonth2   StartDay2  StartYear2   EndMonth2     EndDay2 
##           0           0           0           0           0           0 
##    EndYear2   TransFrom WhereFought   Initiator     Outcome     TransTo 
##           0           0           0           0           0           0 
##     Version 
##           0</code></pre>
<p>We can see the number of NAs in each column: there is only one variable–BatDeath(battle death) with missing value(1 missing).</p>
<p>Figure 1: Visna Graph of Missing Data Pattern for Inter-state Wars Dataset
<img src="finalproj_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>From the visna plot, we can observe that most rows have no variables missing. There is one row with BatDeath(battle death) data missing.</p>
<p>Intra-state Wars Dataset</p>
<pre><code>## SideBDeaths SideADeaths   StartDay1     EndDay1 StartMonth1   EndMonth1 
##         174         171          70          52           9           9 
##      CcodeA    EndYear1      CcodeB   StartDay2     EndDay2   TransFrom 
##           3           2           1           1           1           1 
##      WarNum     WarName     WarType       SideA       SideB       Intnl 
##           0           0           0           0           0           0 
##  StartYear1 StartMonth2  StartYear2   EndMonth2    EndYear2 WhereFought 
##           0           0           0           0           0           0 
##   Initiator     Outcome     TransTo     Version 
##           0           0           0           0</code></pre>
<p>We can see the number of NAs in each column: the two variables with the most missing values are SideBDeaths(174 missing) and SideADeaths(171 missing).</p>
<p>Figure 2: Visna Graph of Missing Data Pattern for Intra-state Wars Dataset
<img src="finalproj_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>We observe that most rows have no missing variables. The most common missing data pattern is having SideADeath and SideBDeath data missing. It’s rare having more than three variables missing in this dataset.</p>
<p>Extra-state Wars Dataset</p>
<pre><code>##      StartDay1        EndDay1       BatDeath      EndMonth1 NonStateDeaths 
##             46             38             15             14             12 
##    StartMonth1      StartDay2        EndDay2         WarNum        WarName 
##             10              1              1              0              0 
##        WarType         ccode1          SideA         ccode2          SideB 
##              0              0              0              0              0 
##     StartYear1       EndYear1    StartMonth2     StartYear2      EndMonth2 
##              0              0              0              0              0 
##       EndYear2      Initiator       Interven      TransFrom        Outcome 
##              0              0              0              0              0 
##        TransTo    WhereFought        Version 
##              0              0              0</code></pre>
<p>We can see the number of NAs in each column: the two variables with the most missing values are StartDay1(46 missing) and EndDay1(38 missing).</p>
<p>Figure 3: Visna Graph of Missing Data Pattern for Extra-state Wars Dataset
<img src="finalproj_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>We observe that most rows have no missing variables. The most common missing data pattern is having StartDay1(the day on which sustained combat began) data missing. It’s rare having more than two variables missing in this dataset.</p>
<p>Non-state Wars Dataset</p>
<pre><code>##       SideBDeaths       SideADeaths TotalCombatDeaths          StartDay 
##                39                38                32                29 
##            EndDay        StartMonth          EndMonth            WarNum 
##                20                16                11                 0 
##           WarName           WarType       WhereFought            SideA1 
##                 0                 0                 0                 0 
##            SideA2            SideB1            SideB2            SideB3 
##                 0                 0                 0                 0 
##            SideB4            SideB5         StartYear           EndYear 
##                 0                 0                 0                 0 
##         Initiator         TransFrom           TransTo           Outcome 
##                 0                 0                 0                 0 
##           Version 
##                 0</code></pre>
<p>We can see the number of NAs in each column: the three variables with the most missing values are SideBDeaths(39 missing), SideADeaths(38 missing) and TotalCombatDeaths(32).</p>
<p>Figure 4: Visna Graph of Missing Data Pattern for Non-state Wars Dataset
<img src="finalproj_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>We observe that there are more rows with missing data than without missing data. The most common missing data pattern is having SideADeath, SideBDeath and TotalCombatDeaths data missing. We also observe that if we have SideADeaths, SideBDeaths missing, then we often also have TotalCombatDeaths missing which makes sense since TotalCombatDeaths is the sum of SideADeath and SideBDeath.</p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-transformation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="results.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/wuyn639/warsinhistory/edit/master/04-missing.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/wuyn639/warsinhistory/blob/master/04-missing.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
